---
- name: Add User and Authorized Keys
  hosts: "*"
  become: true
  vars:
    new_username: dheerajpotluri

  tasks:
    - name: Create the new user
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Ensure the .ssh directory exists for the new user
      file:
        path: "/home/{{ new_username }}/.ssh"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: "0700"

    - name: Add the SSH public key to authorized_keys
      authorized_key:
        user: "{{ new_username }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add the new user to the sudo group
      user:
        name: "{{ new_username }}"
        groups: sudo
        append: yes

    - name: Configure passwordless sudo for the new user
      lineinfile:
        dest: /etc/sudoers
        line: "{{ new_username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory
        mode: 0755
