- hosts: "*"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: Install sudo package
      package:
        name: sudo
        state: present
